/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sangeethlabs_jni_Fortran */

#ifndef _Included_com_sangeethlabs_jni_Fortran
#define _Included_com_sangeethlabs_jni_Fortran
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sangeethlabs_jni_Fortran
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sangeethlabs_jni_Fortran_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
